# Generated by Django 4.2.3 on 2023-07-09 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tarea_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.ManyToManyField(to='app.observacion'),
        ),
    ]
