# Generated by Django 4.2.3 on 2023-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teLoEnvioApp', '0002_usuarios_remove_productor_email_remove_productor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(default='', max_length=10),
        ),
    ]
