# Generated by Django 4.2.3 on 2023-07-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teLoEnvioApp', '0003_usuarios_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirreccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teLoEnvioApp.productor'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teLoEnvioApp.cliente'),
        ),
    ]
