# Generated by Django 4.2.3 on 2023-07-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teLoEnvioApp', '0004_cliente_usuarios_productor_usuarios_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dirreccion',
            new_name='direccion',
        ),
    ]
